replicaCount: 1

image:
  repository: sergeytemkin/quakewatch
  tag: v2
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 5000

containerPort: 5000

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 128Mi

probes:
  liveness:
    path: /health
    initialDelaySeconds: 10
    periodSeconds: 10
  readiness:
    path: /ping
    initialDelaySeconds: 5
    periodSeconds: 10

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

cronjob:
  enabled: true
  schedule: "*/2 * * * *"

config:
  LOG_LEVEL: "debug"

secrets:
  apiKey: ""

hooks:
  postSyncSmokeTest:
    enabled: true
