replicaCount: 2

image:
  repository: sergeytemkin/quakewatch    # Your Docker Hub repo
  tag: "v1"                              # The tag you pulled
  pullPolicy: IfNotPresent

containerPort: 5000

service:
  type: ClusterIP
  port: 80

probes:
  # Your app returns 200 OK on "/"
  liveness:
    path: /
    initialDelaySeconds: 10
    periodSeconds: 10
  readiness:
    path: /
    initialDelaySeconds: 5
    periodSeconds: 5

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"

config:
  LOG_LEVEL: "info"

# Leave empty to skip creating a Secret. Set a string to create it.
secrets:
  apiKey: ""

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50

cronjob:
  enabled: true
  schedule: "*/1 * * * *"
