apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quakewatch
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Sergey-Temkin/QuakeWatch.git
    targetRevision: main
    path: k8s/helm/quakewatch
    helm:
      # OPTIONAL: override/lock key values from your chart (safe to keep as-is)
      values: |
        image:
          repository: sergeytemkin/quakewatch
          tag: v2
        service:
          type: NodePort
          port: 5000
        hpa:
          enabled: true
          minReplicas: 1
          maxReplicas: 5
          targetCPUUtilizationPercentage: 80
        cronjob:
          enabled: true
          schedule: "*/2 * * * *"
        probes:
          liveness:
            path: /health
            initialDelaySeconds: 10
            periodSeconds: 10
          readiness:
            path: /ping
            initialDelaySeconds: 5
            periodSeconds: 10
  destination:
    server: https://kubernetes.default.svc
    namespace: quakewatch
  syncPolicy:
    automated:
      prune: true       # delete cluster objects removed from Git
      selfHeal: true    # revert drifted changes in-cluster
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
